### ISSUE TITLE
Incorrect path to chosen-sprite.png

### ISSUE THREAD

**Issue by octoquad** [syntacticvexation/redmine_favourite_projects#46]
In the logs: ActionController::RoutingError (No route matches [GET] "/plugin_assets/redmine_favourite_projects/stylesheets/chosen-sprite.png").

The image file actually resides in images/ not stylesheets/.

**Comment by octoquad** [comment]
I see a merge request is available to fix this #45.

**Comment by syntacticvexation** [comment]
Thanks, all merged in.

**Comment by octoquad** [comment]
Thanks
