### ISSUE TITLE
Can Not Stop User Override Plugin Global Settings

### ISSUE THREAD

**Issue by johnroyer** [syntacticvexation/redmine_favourite_projects#49]
Error occurs in Redmine `3.0.1.stable` with `redmine_favourite_projects` in `0.8-unstable`.

After plugin installed, all options in the plugin configure page is unchecked as default. Leave all settings unchange. (change settings will rise error descript in issue #48) At this time, `Allow users to override these settings` is unchecked. User should not see plugin settings or change settings in `My account` page.

Follow this steps:

1. login Redemine with a non-administrator account
1. go to `My account` -> `Favorite Projects`
1. It shows `Customise Favorite Project Display` block in page. (should not display or checkbox should be unavailable)
1. add some projects as favorite projects.
1. check `Display favorites on top menu` option and apply settings.
1. favorite projects show on top menu. (user should not override global settings)

**Comment by johnroyer** [comment]
I use non-administrator account to do functional test. Seems all functionality is work fine by using account settings.

**Comment by syntacticvexation** [comment]
Fantastic work as always. :) I found an issue with the global settings not rendering the current setting values, I've pushed the fix to the unstable branch.  The default is to allow users to update their own settings but this wasn't rendering.  Can you check and see if that addresses this issue?  I'm still trying to reproduce #48.  Can you give a bit more context about the data set you're using?  I'm using an updated version of syntacticvexation/redmine_favourite_projects_redmine_fixtures, I can adapt as appropriate if I can get some more info.

**Comment by johnroyer** [comment]
If it allow users to override default settings on global default settings, this may a false positive on the test. Do you know where the plugin config data save in database? I can checkout the actual config and confirm again.

I don't know what exactly `redmine_favourite_projects_redmine_fixtures` does. Could you give me a simple introduction? I use simple install steps to install `redmine_favorite_projects`. After going to plugin configure page, error occurs. What error message should I provide which can make you confirm the issue more quickly?

**Comment by syntacticvexation** [comment]
I think it's enabled but the version you tested just wasn't showing you which items were configured by default, I've hopefully fixed the problem if you do a git pull and rerun the test.

So I don't think it saves in the database until a user makes a change to the plugin settings.  The Settings model has a helper function so you don't have to worry about it.  If you open up a rails console session, you can find out what settings it thinks are enabled (either via the DB or by default) by running:
Setting.plugin_redmine_favourite_projects

I've been using fixtures to setup a database configuration for testing the plugin.  They're just yml files that describe database rows that can be imported to automatically populate the database.  I had problems using Redmine's default fixtures (some of them are just plain broken) so I got a working subset of fixtures and altered some of them for favourite_projects.  So if you move the Redmine test/fixtures directory somewhere safe, if you do a checkout of the favourite_projects fixtures repo you can use, add to the test data I'm using.

In any case, do a pull of the latest version and let me know how you get on.  Thanks heaps.

**Comment by johnroyer** [comment]
Well .... I have not learn Ruby before. I am not sure if I can fix this bug recently. 

I will read the source code first and try to understand how it works first. Seems Redmine can configure loggin level. It may help me out. I will let you know the problems and situation via email. 
Thanks.

**Comment by syntacticvexation** [comment]
Closed as stale.  This is now in a stable release.  Will break fix if this occurs for others.
