### ISSUE TITLE
redmine_favourite_projects

### ISSUE THREAD

**Issue by olemissrebel** [syntacticvexation/redmine_favourite_projects#51]
Hello,

We like this plugin, however in version 2.6.5, it breaks the due date calendar selector for all new issues. Please provide a work around, if it is possible.

SuSE 11sp3

 # rvm -v
rvm 1.26.11 (latest) 

 # ruby -v
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]

 # gem -v
2.4.1

 # rails -v
Rails 3.2.21

Thanks for your time!

**Comment by syntacticvexation** [comment]
Hi,

Thanks for your interest in the plugin.  I'll set my devel environment to the following and try and put out a fix sometime this week.

Cheers.

**Comment by syntacticvexation** [comment]
I've had a look using the same Redmine/Rails version but I'm unable to reproduce this issue.  Can you provide a screenshot of the issue as well as the output from the Redmine log?  Also if there's any errors that come from the Javascript console, it can assist in identifying and reproducing the issue.

Thanks.
