### ISSUE TITLE
Reduce layout in top menu from three to two lines

### ISSUE THREAD

**Issue by jwciss** [syntacticvexation/redmine_favourite_projects#52]
In the top menu, links to favourite projects are currently inserted in between the top links to projects and administration / help, resulting in three lines. How could this be changed so only two lines are used?

Default layout without plugin:

```
Main Page - Projects - Administration - Help
```

Layout with plugin:

```
Main Page - Projects 
Favourite1 - Favourite 2 - Favourite 3 - etc
Administration - Help
```

Proposed change:

```
Main Page - Projects - Administration - Help
Favourite1 - Favourite 2 - Favourite 3 - etc
```

**Comment by jwciss** [comment]
I realized that this effect is only present when using the PurpleMine2 theme (https://github.com/mrliptontea/PurpleMine2). I am not sure whether the theme CSS settings or general settings with this plugin are causing the line break:

![favourites_three_lines](https://cloud.githubusercontent.com/assets/18282521/14348604/ed77f3b4-fcbd-11e5-97d8-c63f7dde460e.PNG)

**Comment by syntacticvexation** [comment]
I've changed how this functionality is written in order to cater for Redmine 3.3, if this is no longer a problem with the 0.9-unstable code base, I'll close this issue.

**Comment by syntacticvexation** [comment]
I've not heard any more on this so I'm closing the issue.  Feel free to reopen if this reoccurs.

**Comment by jwciss** [comment]
We had manually changed the CSS in the theme and have not upgraded this plugin to the current version yet. If we still encounter problems after we do, I will let you know.
