### ISSUE TITLE
Links are not displayed in the topbar, but in bottom of each page

### ISSUE THREAD

**Issue by JL2014** [syntacticvexation/redmine_favourite_projects#55]
Hi,

I have upgraded my redmine to the last version.
Before the favourite links were displayed in the topbar without problem.
After the links are not in the top bar, but all the links are in the bottom of each page.

I have cleared cache browser, the problem persist.

Maybe a CSS issue ?

Grretings.

**Comment by syntacticvexation** [comment]
Hi,

Can you confirm what Redmine version you are using and whether you're using a theme or just the default?

**Comment by aetebbe** [comment]
I am seeing the same issue (links at bottom of the page).  Recently migrated to redmine 3.3 and am running 0.8.2.
Is redmine 3.x supported?

**Comment by aetebbe** [comment]
One of my developers was able to get it to work with redmine 3.3 with this patch:
diff --git a/init.rb b/init.rb
index 9a2f00f..e227947 100755
--- a/init.rb
+++ b/init.rb
@@ -62,7 +62,7 @@ Redmine::Plugin.register :redmine_favourite_projects do
     },
     :partial => 'redmine_favourite_projects'

-  menu :top_menu, :favourite_menu, '',
+  menu :top_menu, :favourite_menu, { :controller => 'favourite_projects', :action => 'index' },
   {
     :caption => '',
     :html => { :id => 'favourite-menu' },

**Comment by syntacticvexation** [comment]
I've investigated this issue and rewritten this component to patch Redmine internally rather than use the menu mechanism (as this isn't well designed to handle menu items that change between page refreshes).  I've put this change on the 0.9-unstable branch if you could take a look and let me know if it works for you, I'll make this a stable release.

**Comment by L0rD59** [comment]
Hi,

i was the same problem and this patch works fine for me.

Thx a lot

**Comment by aetebbe** [comment]
0.9-unstable works for us - thanks!
