### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jwciss** [syntacticvexation/redmine_favourite_projects#56]
Several changes have been made to the master branch since the last release on Nov 7, 2014. When can an up-to-date regular release be expected?

**Comment by syntacticvexation** [comment]
Hi.  I've tagged the state of master as of when the issue was posted as 0.7.1-stable.  I've rolled the other feature branch back into the mainline as the latest release 0.8-stable.  I'll take a look at the presentation changes for 0.8.1.

**Comment by jwciss** [comment]
Thank you!
