### ISSUE TITLE
French translation for version 0.9

### ISSUE THREAD

**Issue by lhadjadj** [syntacticvexation/redmine_favourite_projects#58]
Hi, this is the french translation for the version 0.9.
[fr.zip](https://github.com/syntacticvexation/redmine_favourite_projects/files/583546/fr.zip)

**Comment by syntacticvexation** [comment]
Rolled into 0.9.1-stable (https://github.com/syntacticvexation/redmine_favourite_projects/releases/tag/0.9.1-stable).  Thanks. :-)
