### ISSUE TITLE
French translation update (minor spelling corrections)

### ISSUE THREAD

**Issue by lhadjadj** [syntacticvexation/redmine_favourite_projects#60]
Hi, Happy new Year :)

This is the french translation for the version 0.9.1, the same minus some spelling mistakes. So it will fine in the next release.
Thx
[fr.zip](https://github.com/syntacticvexation/redmine_favourite_projects/files/702404/fr.zip)

**Comment by syntacticvexation** [comment]
Great, thanks.  Rolled into 0.9.2 release.
