### ISSUE TITLE
Favourite projects does not appear on top menu

### ISSUE THREAD

**Issue by lbayerlein** [syntacticvexation/redmine_favourite_projects#67]
Hi,

thanks for this simple, but awesome plugin. It helps us to get more productive in our workflow :)

I have installed the redmineup agile plugin on our redmine 4.x and after this, our favourite projects does not appear any more in the top menu. Can you give me some advice to solve this?

Thanks very much

**Comment by jcormier** [comment]
I am also seeing this on redmine 4.1.3 and 4.1.5

**Comment by jcormier** [comment]
I removed the redmine agile plugin but I don't see the favourites section in the dropdown.  So I don't think its the issue.

![image](https://user-images.githubusercontent.com/5613721/139922934-ce04edc8-cb80-4aba-a5d7-58d7d9a7e3e8.png)

**Comment by jcormier** [comment]
It looks like the bookmarks feature, makes this plugin obsolete anyways.
https://www.redmine.org/issues/31355
